apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cosmic-guestbook-pipeline
description: Cosmic Guestbook delivery pipeline
serialPipeline:
  stages:
    - targetId: prod
      profiles: []
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          canaryDeployment:
            percentages: [10]
            verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production Cloud Run service
run:
  location: projects/__PROJECT_ID__/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: cosmic-guestbook-pipeline/auto-advance
serviceAccount: __PROJECT_NUMBER__-compute@developer.gserviceaccount.com
selector:
  targets:
  - id: prod
rules:
- advanceRolloutRule:
    id: "advance-rule"
    wait: 1m
