---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cosmic-guestbook-prod
  annotations:
    run.googleapis.com/invoker-iam-disabled: 'true'
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
        - name: cosmic-guestbook-1
          image: cosmic-guestbook
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: "REPLACED_BY_DEPLOY"  # from-param: ${PROJECT_ID}
        - name: go-feature-flag-1
          image: gofeatureflag/go-feature-flag:latest
          env:
            - name: RETRIEVERS_0_KIND
              value: github
            - name: RETRIEVERS_0_REPOSITORYSLUG
              value: "REPLACED_BY_DEPLOY"  # from-param: ${REPOSITORY_SLUG}
            - name: RETRIEVERS_0_PATH
              value: flags.yaml
            - name: RETRIEVERS_0_BRANCH
              value: demo
            - name: RETRIEVERS_0_POLLINGINTERVAL
              value: "10000"
